In [17]:
# Import library
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests

### Halaman 1

In [18]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search?query={}".format(keyword)

In [21]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [22]:
# Memasukkan hasil scraping ke dalam DataFrame
df1 = pd.DataFrame(data)
df1.head()

,0,1
0,[Pelaksanaan PON XX Beri Dampak Ekonomi bagi M...,/play/b1oCAJZL-pelaksanaan-pon-xx-beri-dampak-...
1,[Harga Minyak Tinggi Bisa Hambat Pemulihan Eko...,/play/NxGCymm4-harga-minyak-tinggi-bisa-hambat...
2,[IMF Pangkas Proyeksi Pertumbuhan Ekonomi Glob...,/play/NleC6BQ2-imf-pangkas-proyeksi-pertumbuha...
3,[Cerita Gagastama Peraih Beasiswa OSC: Tetap B...,/play/koGCG96P-cerita-gagastama-peraih-beasisw...
4,[Kawasan Ekonomi Khusus JIIPE Gresik Resmi Ber...,/play/bmRCy0Dn-kawasan-ekonomi-khusus-jiipe-gr...

In [23]:
# Mengganti nama kolom
df1.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df1.tail()

,Judul Berita,URL
25,[Jokowi Ungkap Tiga Strategi Besar Ekonomi Ind...,/play/NA0C21G2-jokowi-ungkap-tiga-strategi-bes...
26,[DPR Nilai Target Pertumbuhan Ekonomi 2022 di ...,/play/bD2CWnLM-dpr-nilai-target-pertumbuhan-ek...
27,"[Longgarkan Aktivitas Ekonomi, PPKM Tetap Ketat]",/play/kqYCoP2w-longgarkan-aktivitas-ekonomi-pp...
28,"[Ekonomi Indonesia Ditargetkan Tumbuh 5-5,5% d...",/play/NA0C250P-ekonomi-indonesia-ditargetkan-t...
29,[Gubernur NTT Tandatangani Pinjaman Pemulihan ...,/play/bw6C5plJ-gubernur-ntt-tandatangani-pinja...

### Halaman 2

In [25]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/1".format(keyword)

In [26]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [27]:
# Memasukkan hasil scraping ke dalam DataFrame
df2 = pd.DataFrame(data)
df2.head()

,0,1
0,[Komitmen Bank BNI Jaga Pertumbuhan Ekonomi],/play/kBVCRQ8a-komitmen-bank-bni-jaga-pertumbu...
1,[JIIPE Gresik Resmi Jadi Kawasan Ekonomi Khusu...,/play/kqYCo9Qx-jiipe-gresik-resmi-jadi-kawasan...
2,[Lembaga Perkreditan Desa Bantu Ekonomi Warga ...,/play/KXyC0nGV-lembaga-perkreditan-desa-bantu-...
3,[Kades di Bantul Prakarsai Platform Digital un...,/play/bmRCylDW-kades-di-bantul-prakarsai-platf...
4,[Pelonggaran Aktivitas Sosial-Ekonomi di Masa ...,/play/NLMCRpZa-pelonggaran-aktivitas-sosial-ek...

In [28]:
# Mengganti nama kolom
df2.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df2.tail()

,Judul Berita,URL
25,[Kemenkeu Ambil Alih Pelaksanaan Anggaran Perl...,/play/b1oCAnlE-kemenkeu-ambil-alih-pelaksanaan...
26,[Surplus Neraca Perdagangan Jaga Pertumbuhan E...,/play/bw6C5wRx-surplus-neraca-perdagangan-jaga...
27,[BI Pangkas Proyeksi Pertumbuhan Ekonomi Jadi ...,/play/b2lCOJZZ-bi-pangkas-proyeksi-pertumbuhan...
28,[Proyeksi Pertumbuhan Ekonomi 2021 Direvisi Ja...,/play/KvJCQjMl-proyeksi-pertumbuhan-ekonomi-20...
29,[Percepatan Infrastruktur Digital untuk Mengge...,/play/kj2C16Rn-percepatan-infrastruktur-digita...

### Halaman 3

In [29]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/2".format(keyword)

In [30]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [31]:
# Memasukkan hasil scraping ke dalam DataFrame
df3 = pd.DataFrame(data)
df3.head()

,0,1
0,[Kerja Sama Ekonomi Syariah Indonesia-Rusia (5)],/play/b7WCO75e-kerja-sama-ekonomi-syariah-indo...
1,[Kerja Sama Ekonomi Syariah Indonesia-Rusia (4)],/play/NP6CA2JO-kerja-sama-ekonomi-syariah-indo...
2,[Kerja Sama Ekonomi Syariah Indonesia-Rusia (3)],/play/N9nCvA53-kerja-sama-ekonomi-syariah-indo...
3,[Kerja Sama Ekonomi Syariah Indonesia-Rusia (2)],/play/kqYCo3Ww-kerja-sama-ekonomi-syariah-indo...
4,[Kerja Sama Ekonomi Syariah Indonesia-Rusia (1)],/play/b1oCAGvZ-kerja-sama-ekonomi-syariah-indo...

In [32]:
# Mengganti nama kolom
df3.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df3.tail()

,Judul Berita,URL
25,[Airlangga Optimistis Target Pertumbuhan Ekono...,/play/KdZCqL9G-airlangga-optimistis-target-per...
26,[Kenaikan Tarif PPN Membebani Ekonomi],/play/K5nC0yAB-kenaikan-tarif-ppn-membebani-ek...
27,[ISEI Siap Dukung Revitalisasi Ekonomi Maritim],/play/KYVC6lDO-isei-siap-dukung-revitalisasi-e...
28,[Ternak Love Bird Tingkatkan Ekonomi],/play/kBVCRma5-ternak-love-bird-tingkatkan-eko...
29,[UU Cipta Kerja Kuatkan Ekonomi Syariah (4)],/play/NA0C2x7j-uu-cipta-kerja-kuatkan-ekonomi-...

### Halaman 4

In [33]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/3".format(keyword)

In [34]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [35]:
# Memasukkan hasil scraping ke dalam DataFrame
df4 = pd.DataFrame(data)
df4.head()

,0,1
0,[UU Cipta Kerja Kuatkan Ekonomi Syariah (3)],/play/K5nC0yX4-uu-cipta-kerja-kuatkan-ekonomi-...
1,[UU Cipta Kerja Kuatkan Ekonomi Syariah (2)],/play/kewCX7OO-uu-cipta-kerja-kuatkan-ekonomi-...
2,[UU Cipta Kerja Kuatkan Ekonomi Syariah (1)],/play/bmRCy16w-uu-cipta-kerja-kuatkan-ekonomi-...
3,[Produk Ekonomi Kreatif Pati Dipasarkan Hingga...,/play/NrWCRBQX-produk-ekonomi-kreatif-pati-dip...
4,[Ekonomi Kreatif Hidupi Warga Rembang],/play/N6GC02jx-ekonomi-kreatif-hidupi-warga-re...

In [36]:
# Mengganti nama kolom
df4.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df4.tail()

,Judul Berita,URL
25,[Ekonomi Syariah Punya Daya Tahan Cukup Tinggi...,/play/k8oC47nZ-ekonomi-syariah-punya-daya-taha...
26,"[Dinilai Gagal Atasi Krisis Ekonomi, Demonstra...",/play/NleC63A0-dinilai-gagal-atasi-krisis-ekon...
27,[Fundamental Ekonomi Indonesia Dinilai Kuat],/play/KRXCgDLQ-fundamental-ekonomi-indonesia-d...
28,[Bedah Editorial MI: Vaksinasi Sehatkan Ekonomi],/play/kewCX1JO-bedah-editorial-mi-vaksinasi-se...
29,[Vaksinasi Sehatkan Ekonomi],/play/bmRCyQqw-vaksinasi-sehatkan-ekonomi

### Halaman 5

In [37]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/4".format(keyword)

In [38]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [39]:
# Memasukkan hasil scraping ke dalam DataFrame
df5 = pd.DataFrame(data)
df5.head()

,0,1
0,[Kampung Tangguh Desa Bakaran Batu untuk Perba...,/play/NOlCa5XA-kampung-tangguh-desa-bakaran-ba...
1,"[JaFest 2021, Upaya Bangkitkan Ekonomi di Jabar]",/play/N0BClD0M-jafest-2021-upaya-bangkitkan-ek...
2,[Vaksinasi Pegiat Sektor Pariwisata di Bali Ba...,/play/K5nC0AP7-vaksinasi-pegiat-sektor-pariwis...
3,[Bisakah Stimulus Ketiga Pulihkan Ekonomi AS?],/play/kELC8Mpm-bisakah-stimulus-ketiga-pulihka...
4,[Pandemi Covid-19 Mengancam Ketahanan Ekonomi ...,/play/KZmCgRge-pandemi-covid-19-mengancam-keta...

In [40]:
# Mengganti nama kolom
df5.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df5.tail()

,Judul Berita,URL
25,[Rapim TNI 2021 Bahas Penanganan Covid-19 hing...,/play/KRXCg9gy-rapim-tni-2021-bahas-penanganan...
26,[Vaksin Suntik Pemulihan Ekonomi (4)],/play/bw6C5Xqr-vaksin-suntik-pemulihan-ekonomi-4
27,[Vaksin Suntik Pemulihan Ekonomi (3)],/play/bD2CWl22-vaksin-suntik-pemulihan-ekonomi-3
28,[Vaksin Suntik Pemulihan Ekonomi (2)],/play/NLMCRqQe-vaksin-suntik-pemulihan-ekonomi-2
29,[Vaksin Suntik Pemulihan Ekonomi (1)],/play/b2lCO5Dx-vaksin-suntik-pemulihan-ekonomi-1

### Halaman 6

In [41]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/5".format(keyword)

In [42]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [43]:
# Memasukkan hasil scraping ke dalam DataFrame
df6 = pd.DataFrame(data)
df6.head()

,0,1
0,[Kontribusi Pertanian dalam Ekonomi Nasional],/play/kewCXmev-kontribusi-pertanian-dalam-ekon...
1,[Tanda-tanda Pemulihan Ekonomi Indonesia Mulai...,/play/kELC8BLn-tanda-tanda-pemulihan-ekonomi-i...
2,[Airlangga Optimistis Tren Pemulihan Ekonomi B...,/play/KRXCgRPB-airlangga-optimistis-tren-pemul...
3,[Sektor Pertanian Beri Kontribusi Positif Bagi...,/play/kpLCBzeA-sektor-pertanian-beri-kontribus...
4,"[Pertumbuhan Ekonomi RI 2020 Minus 2,07 Persen]",/play/ba4CV67v-pertumbuhan-ekonomi-ri-2020-min...

In [44]:
# Mengganti nama kolom
df6.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df6.tail()

,Judul Berita,URL
25,[Gaung Ekonomi & Keuangan Syariah Lewat Media ...,/play/bVDCQR0m-gaung-ekonomi-keuangan-syariah-...
26,[Gaung Ekonomi & Keuangan Syariah Lewat Media ...,/play/k8oC4Deg-gaung-ekonomi-keuangan-syariah-...
27,[Gaung Ekonomi & Keuangan Syariah Lewat Media ...,/play/NgxCrqmP-gaung-ekonomi-keuangan-syariah-...
28,[Penyaluran Bansos Bantu Ekonomi Warga Terdamp...,/play/NP6CARg7-penyaluran-bansos-bantu-ekonomi...
29,[Moment of The Year 2020 - Ekonomi],/play/bD2CW9oP-moment-of-the-year-2020-ekonomi

### Halaman 7

In [45]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/6".format(keyword)

In [46]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [47]:
# Memasukkan hasil scraping ke dalam DataFrame
df7 = pd.DataFrame(data)
df7.head()

,0,1
0,[Perkuat Daya Saing Global Via Ekonomi Digital],/play/NxGCynq3-perkuat-daya-saing-global-via-e...
1,[Budidaya Lobster Air Tawar Bisa Topang Ekonom...,/play/NxGCyYa2-budidaya-lobster-air-tawar-bisa...
2,[Harapan Pelaku Ekonomi pada Menteri Baru],/play/kWDCd6ap-harapan-pelaku-ekonomi-pada-men...
3,[Pemberdayaan UMKM untuk Pemulihan Ekonomi],/play/b3JCVgzd-pemberdayaan-umkm-untuk-pemulih...
4,[Meraih Peluang Pemulihan Ekonomi 2021],/play/kM6CQ754-meraih-peluang-pemulihan-ekonom...

In [48]:
# Mengganti nama kolom
df7.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df7.tail()

,Judul Berita,URL
25,[Wanita Penegak Ekonomi Syariah (3)],/play/NleC6PO5-wanita-penegak-ekonomi-syariah-3
26,[Daya Ungkit Ekonomi Pilkada 2020 Sangat Minim...,/play/ba4CVWrQ-daya-ungkit-ekonomi-pilkada-202...
27,[Hari Nusantara 2020: Potensi Bahari untuk Eko...,/play/KdZCqpvL-hari-nusantara-2020-potensi-bah...
28,[Kehadiran Vaksin Covid-19 Dorong Pemulihan Ek...,/play/bD2CWJon-kehadiran-vaksin-covid-19-doron...
29,[Vaksin Covid-19 Topang Pemulihan Ekonomi],/play/bzGCpD15-vaksin-covid-19-topang-pemuliha...

### Halaman 8

In [49]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/7".format(keyword)

In [50]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [51]:
# Memasukkan hasil scraping ke dalam DataFrame
df8 = pd.DataFrame(data)
df8.head()

,0,1
0,[OECD: Vaksin Covid-19 Bawa Optimisme Pemuliha...,/play/NOlCayLa-oecd-vaksin-covid-19-bawa-optim...
1,[Proyek Hulu Migas yang Menggerakkan Ekonomi],/play/N0BClgR5-proyek-hulu-migas-yang-menggera...
2,[Dukungan Bank Himbara Dorong Pemulihan Ekonom...,/play/NnjCdRGr-dukungan-bank-himbara-dorong-pe...
3,[Konsumsi Rumah Tangga Dorong Pemulihan Ekonom...,/play/koGCGgmB-konsumsi-rumah-tangga-dorong-pe...
4,"[Memberi Energi, Menggerakkan Ekonomi]",/play/kpLCBvRG-memberi-energi-menggerakkan-eko...

In [52]:
# Mengganti nama kolom
df8.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df8.tail()

,Judul Berita,URL
25,[Kontribusi Fintech pada Ekonomi RI],/play/kM6CQ46y-kontribusi-fintech-pada-ekonomi-ri
26,[Kerja Sama Ekonomi Internasional Tiongkok],/play/bzGCpeqE-kerja-sama-ekonomi-internasiona...
27,[Sektor Pertanian Bisa Jadi Daya Ungkit Ekonomi],/play/NgxCrawa-sektor-pertanian-bisa-jadi-daya...
28,[Daya Ungkit Ekonomi Program PEN],/play/kewCXj03-daya-ungkit-ekonomi-program-pen
29,[Imbas Kemenangan Biden Terhadap Ekonomi RI],/play/NG9CazjQ-imbas-kemenangan-biden-terhadap...

### Halaman 9

In [53]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/8".format(keyword)

In [54]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [55]:
# Memasukkan hasil scraping ke dalam DataFrame
df9 = pd.DataFrame(data)
df9.head()

,0,1
0,[Xi Jinping Buka Peluang Kerja Sama Global unt...,/play/b1oCAOMo-xi-jinping-buka-peluang-kerja-s...
1,[Pemprov Babel Bantu Pemulihan Ekonomi Nasiona...,/play/bJECzjEl-pemprov-babel-bantu-pemulihan-e...
2,[Momentum Indonesia Pulihkan Ekonomi],/play/NgxCrajB-momentum-indonesia-pulihkan-eko...
3,[Kondisi Ekonomi Indonesia Kuartal III Membaik],/play/NOlCa9j3-kondisi-ekonomi-indonesia-kuart...
4,"[Resmi Resesi, Ekonomi Indonesia Minus 3,49 Pe...",/play/b7WCOmVr-resmi-resesi-ekonomi-indonesia-...

In [56]:
# Mengganti nama kolom
df9.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df9.tail()

,Judul Berita,URL
25,[Ratusan Warga Beirut Turun ke Jalan Protes Pe...,/play/NgxCrDjO-ratusan-warga-beirut-turun-ke-j...
26,[Pemulihan Ekonomi Nasional Tiongkok],/play/bD2CWMlv-pemulihan-ekonomi-nasional-tion...
27,[Evaluasi Kinerja Satu Tahun Jokowi-Amin di Se...,/play/b7WCOgw8-evaluasi-kinerja-satu-tahun-jok...
28,[Indonesia Diklaim Masuk Lima Besar Penanganan...,/play/N9nCv2YD-indonesia-diklaim-masuk-lima-be...
29,[Dampak Omnibus Law pada Pemulihan Ekonomi],/play/bD2CWM9R-dampak-omnibus-law-pada-pemulih...

### Halaman 10

In [57]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/9".format(keyword)

In [58]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [59]:
# Memasukkan hasil scraping ke dalam DataFrame
df10 = pd.DataFrame(data)
df10.head()

,0,1
0,[Gerakan Ekonomi Sirkular di Pulau Komodo],/play/K5nC07gG-gerakan-ekonomi-sirkular-di-pul...
1,[Xi Jinping Hadiri Perayaan 40 Tahun Zona Ekon...,/play/kBVCR9l4-xi-jinping-hadiri-perayaan-40-t...
2,[UU Ciptaker Picu Pemulihan Ekonomi Nasional],/play/bzGCpR2e-uu-ciptaker-picu-pemulihan-ekon...
3,[Pemerintah Harapkan Koperasi Bantu Pemulihan ...,/play/NQAC3YqO-pemerintah-harapkan-koperasi-ba...
4,[Indonesia Masuk Lima Besar Penanganan Covid-1...,/play/kj2C1E1j-indonesia-masuk-lima-besar-pena...

In [60]:
# Mengganti nama kolom
df10.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df10.tail()

,Judul Berita,URL
25,[Rakorpim untuk Pemulihan Ekonomi Nasional],/play/bVDCQgy7-rakorpim-untuk-pemulihan-ekonom...
26,[Pengawal Ekonomi dan Keuangan Syariah Indones...,/play/kewCXawn-pengawal-ekonomi-dan-keuangan-s...
27,[Pengawal Ekonomi dan Keuangan Syariah Indones...,/play/bmRCyexZ-pengawal-ekonomi-dan-keuangan-s...
28,[Pengawal Ekonomi dan Keuangan Syariah Indones...,/play/bzGCpzD1-pengawal-ekonomi-dan-keuangan-s...
29,[Pengawal Ekonomi dan Keuangan Syariah Indones...,/play/bw6C5oRd-pengawal-ekonomi-dan-keuangan-s...

### Halaman 11

In [61]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/10".format(keyword)

In [62]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [63]:
# Memasukkan hasil scraping ke dalam DataFrame
df11 = pd.DataFrame(data)
df11.head()

,0,1
0,[Pengawal Ekonomi dan Keuangan Syariah Indones...,/play/bD2CW1Jr-pengawal-ekonomi-dan-keuangan-s...
1,"[Pengamat Ekonomi: Resesi, Jangan Khawatir Itu...",/play/KRXCg5Qy-pengamat-ekonomi-resesi-jangan-...
2,[Indonesia Masuk Zona Resesi Ekonomi],/play/bmRCyeeO-indonesia-masuk-zona-resesi-eko...
3,[Realisasi Anggaran Pemulihan Ekonomi Nasional...,/play/bD2CW1Zq-realisasi-anggaran-pemulihan-ek...
4,[Realisasi Anggaran Pemulihan Ekonomi Nasional...,/play/N0BClvO6-realisasi-anggaran-pemulihan-ek...

In [64]:
# Mengganti nama kolom
df11.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df11.tail()

,Judul Berita,URL
25,[Perbandingan Kondisi & Indikator Ekonomi 1998...,/play/kBVCR2jQ-perbandingan-kondisi-indikator-...
26,[Satgas PEN: Pencairan Dana Program Stimulus E...,/play/bJECznq6-satgas-pen-pencairan-dana-progr...
27,[Siasat Mendorong Perbaikan Ekonomi],/play/NleC60Mn-siasat-mendorong-perbaikan-ekonomi
28,[Aktivitas Ekonomi Belum Stabil],/play/NxGCy5qj-aktivitas-ekonomi-belum-stabil
29,[Menkeu Prediksi Pertumbuhan Ekonomi Kuartal I...,/play/NA0C2XY9-menkeu-prediksi-pertumbuhan-eko...

### Halaman 12

In [65]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/11".format(keyword)

In [66]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [67]:
# Memasukkan hasil scraping ke dalam DataFrame
df12 = pd.DataFrame(data)
df12.head()

,0,1
0,[Realisasi Anggaran Ekonomi Nasional pada Agus...,/play/kM6CQ0pj-realisasi-anggaran-ekonomi-nasi...
1,[Gerak Cepat Ekonomi Melesat (6)],/play/bzGCpgvj-gerak-cepat-ekonomi-melesat-6
2,[Gerak Cepat Ekonomi Melesat (5)],/play/bw6C5Yd6-gerak-cepat-ekonomi-melesat-5
3,[Gerak Cepat Ekonomi Melesat (4)],/play/bD2CWZ77-gerak-cepat-ekonomi-melesat-4
4,[Gerak Cepat Ekonomi Melesat (3)],/play/NLMCROPL-gerak-cepat-ekonomi-melesat-3

In [68]:
# Mengganti nama kolom
df12.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df12.tail()

,Judul Berita,URL
25,"[Pertumbuhan Ekonomi Kuartal II/2020 Minus 5,3...",/play/NleC66Od-pertumbuhan-ekonomi-kuartal-ii-...
26,[Proyeksi Pertumbuhan Ekonomi Indonesia di Kua...,/play/NA0C22wv-proyeksi-pertumbuhan-ekonomi-in...
27,[IHSG Tertekan Buruknya Prospek Ekonomi Global],/play/NnjCddg7-ihsg-tertekan-buruknya-prospek-...
28,[Realisasi Penyerapan Dana Pemulihan Ekonomi B...,/play/NxGCyO82-realisasi-penyerapan-dana-pemul...
29,[Ekonomi Indonesia Diprediksi Cepat Pulih Sete...,/play/bVDCQw90-ekonomi-indonesia-diprediksi-ce...

### Halaman 13

In [69]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/12".format(keyword)

In [70]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [71]:
# Memasukkan hasil scraping ke dalam DataFrame
df13 = pd.DataFrame(data)
df13.head()

,0,1
0,[Jokowi Minta APBN 2021 Fokus Percepatan Pemul...,/play/KvJCQYzl-jokowi-minta-apbn-2021-fokus-pe...
1,[PT SMI Salurkan Pinjaman ke Daerah untuk Pemu...,/play/kBVCRj70-pt-smi-salurkan-pinjaman-ke-dae...
2,[Bappenas Tinjau Pemulihan Ekonomi Labuan Bajo],/play/NrWCRlAq-bappenas-tinjau-pemulihan-ekono...
3,[Ekonomi Indonesia Diproyeksi Membaik di Semes...,/play/bVDCQwEj-ekonomi-indonesia-diproyeksi-me...
4,[Ekonomi Korea Selatan Resesi],/play/kWDCd9q9-ekonomi-korea-selatan-resesi

In [72]:
# Mengganti nama kolom
df13.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df13.tail()

,Judul Berita,URL
25,[Peluang Ekonomi dari Sampah Plastik],/play/bzGCpXJ5-peluang-ekonomi-dari-sampah-pla...
26,"[Jadi Penggerak Ekonomi, Presiden Dorong Jajar...",/play/kM6CQz1n-jadi-penggerak-ekonomi-presiden...
27,[Peluang Ekonomi Daur Ulang Sampah Plastik],/play/KdZCqO7M-peluang-ekonomi-daur-ulang-samp...
28,[Ekonomi Global Dorong IHSG dan Rupiah ke Zona...,/play/KZmCg01p-ekonomi-global-dorong-ihsg-dan-...
29,"[Jaga Geliat Ekonomi Warga di Masa Pandemi, Wa...",/play/NG9Ca9qj-jaga-geliat-ekonomi-warga-di-ma...

### Halaman 14

In [73]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/13".format(keyword)

In [74]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [75]:
# Memasukkan hasil scraping ke dalam DataFrame
df14 = pd.DataFrame(data)
df14.head()

,0,1
0,[IMF Revisi Proyeksi Ekonomi Dunia],/play/NrWCRQrW-imf-revisi-proyeksi-ekonomi-dunia
1,"[Hadiri KTT ASEAN, Jokowi Usulkan ASEAN Travel...",/play/b2lCOoJX-hadiri-ktt-asean-jokowi-usulkan...
2,[Perbaikan Ekonomi Melalui Kredit Perbankan],/play/bVDCQ0nZ-perbaikan-ekonomi-melalui-kredi...
3,[Bedah Editorial MI: Menyelaraskan Kesehatan d...,/play/koGCGy2O-bedah-editorial-mi-menyelaraska...
4,[Menyelaraskan Kesehatan dan Ekonomi],/play/KYVC6rMq-menyelaraskan-kesehatan-dan-eko...

In [76]:
# Mengganti nama kolom
df14.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df14.tail()

,Judul Berita,URL
25,[New Normal Dinilai akan Berdampak Positif pad...,/play/kqYCoBaP-new-normal-dinilai-akan-berdamp...
26,[Melek Ekonomi Syariah (4)],/play/kpLCB93n-melek-ekonomi-syariah-4
27,[Melek Ekonomi Syariah (3)],/play/kELC8RMZ-melek-ekonomi-syariah-3
28,[Melek Ekonomi Syariah (2)],/play/N4EC85Y6-melek-ekonomi-syariah-2
29,[Melek Ekonomi Syariah (1)],/play/bJECzLl8-melek-ekonomi-syariah-1

### Halaman 15

In [77]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/14".format(keyword)

In [78]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [79]:
# Memasukkan hasil scraping ke dalam DataFrame
df15 = pd.DataFrame(data)
df15.head()

,0,1
0,[Skema Ekonomi dan Panduan New Normal],/play/kpLCB9xE-skema-ekonomi-dan-panduan-new-n...
1,[Dana Pemulihan Ekonomi Bagi BUMN],/play/bVDCQv2j-dana-pemulihan-ekonomi-bagi-bumn
2,[Sri Mulyani Ibaratkan Kesehatan & Ekonomi Sep...,/play/NA0C2wBZ-sri-mulyani-ibaratkan-kesehatan...
3,"[Kuartal I 2020, Ekonomi DKI Jakarta Tumbuh 5,...",/play/NrWCR9lz-kuartal-i-2020-ekonomi-dki-jaka...
4,"[Ekonomi Nasional Terdampak Covid-19, Rp 641 T...",/play/NnjCdZlX-ekonomi-nasional-terdampak-covi...

In [80]:
# Mengganti nama kolom
df15.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df15.tail()

,Judul Berita,URL
25,[Kebijakan Ekonomi Saat Pandemi Covid-19],/play/NLMCRY6R-kebijakan-ekonomi-saat-pandemi-...
26,[Dampak Ekonomi Pandemi Covid-19],/play/NP6CAg1r-dampak-ekonomi-pandemi-covid-19
27,[BI Paparkan Perkembangan Ekonomi Terkini],/play/b2lCOE67-bi-paparkan-perkembangan-ekonom...
28,[Aktivitas Ekonomi Warga di Purwakarta Terhamb...,/play/N4EC8q56-aktivitas-ekonomi-warga-di-purw...
29,"[Masih Kaji Dampak Ekonomi, Penghentian Operas...",/play/KdZCqmmd-masih-kaji-dampak-ekonomi-pengh...

### Halaman 16

In [81]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/15".format(keyword)

In [82]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [83]:
# Memasukkan hasil scraping ke dalam DataFrame
df16 = pd.DataFrame(data)
df16.head()

,0,1
0,[Pemberian Insentif Bantu Ekonomi Masyarakat],/play/kWDCd7Vz-pemberian-insentif-bantu-ekonom...
1,[Indonesia Townhall - Kendali Ekonomi Melawan ...,/play/b2lCOE88-indonesia-townhall-kendali-ekon...
2,[Indonesia Townhall - Kendali Ekonomi Melawan ...,/play/NrWCRdaa-indonesia-townhall-kendali-ekon...
3,[Indonesia Townhall - Kendali Ekonomi Melawan ...,/play/KRXCgnZL-indonesia-townhall-kendali-ekon...
4,[Indonesia Townhall - Kendali Ekonomi Melawan ...,/play/NxGCyvrZ-indonesia-townhall-kendali-ekon...

In [84]:
# Mengganti nama kolom
df16.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df16.tail()

,Judul Berita,URL
25,[Rencana Stimulus Ekonomi Jilid II],/play/bzGCpJp8-rencana-stimulus-ekonomi-jilid-ii
26,[Kebijakan Sejumlah Negara Mengantisipasi Damp...,/play/KZmCgexJ-kebijakan-sejumlah-negara-menga...
27,[Indonesia-Belanda Perkuat Kerja Sama Ekonomi ...,/play/kBVCREe4-indonesia-belanda-perkuat-kerja...
28,"[Ekonomi RI Diprediksi Terkoreksi 0,6% Akibat ...",/play/bw6C5WJg-ekonomi-ri-diprediksi-terkoreks...
29,[Dampak Virus Corona pada Ekonomi Global],/play/kM6CQy8V-dampak-virus-corona-pada-ekonom...

### Halaman 17

In [85]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/16".format(keyword)

In [86]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [87]:
# Memasukkan hasil scraping ke dalam DataFrame
df17 = pd.DataFrame(data)
df17.head()

,0,1
0,[Pemerintah Tambah Hari Libur dan Cuti Bersama...,/play/KYVC6RgQ-pemerintah-tambah-hari-libur-da...
1,[Moody's Pangkas Proyeksi Pertumbuhan Ekonomi ...,/play/KXyC0Xdr-moody-s-pangkas-proyeksi-pertum...
2,[Jokowi Optimis Omnibus Law Cipta Kerja Pacu P...,/play/NG9CaEAj-jokowi-optimis-omnibus-law-cipt...
3,[Dampak Ekonomi Virus Corona Dinilai Lebih Ser...,/play/b3JCVEZE-dampak-ekonomi-virus-corona-din...
4,[Gotong Royong Bangun Ekonomi Indonesia],/play/NgxCr5nd-gotong-royong-bangun-ekonomi-in...

In [88]:
# Mengganti nama kolom
df17.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df17.tail()

,Judul Berita,URL
25,[Cegah Dampak Ekonomi Virus Corona (3)],/play/KvJCQloG-cegah-dampak-ekonomi-virus-coro...
26,[Cegah Dampak Ekonomi Virus Corona (2)],/play/NleC6M15-cegah-dampak-ekonomi-virus-coro...
27,[Cegah Dampak Ekonomi Virus Corona (1)],/play/koGCG4zn-cegah-dampak-ekonomi-virus-coro...
28,[Bedah Editorial MI: Kelola Dampak Ekonomi Vir...,/play/KXyC0pBV-bedah-editorial-mi-kelola-dampa...
29,[Kelola Dampak Ekonomi Virus Corona],/play/kpLCBAl7-kelola-dampak-ekonomi-virus-corona

### Halaman 18

In [94]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/17".format(keyword)

In [95]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [96]:
# Memasukkan hasil scraping ke dalam DataFrame
df18 = pd.DataFrame(data)
df18.head()

,0,1
0,[Dampak Ekonomi Pasca-Wabah Virus Corona],/play/bJECz51d-dampak-ekonomi-pasca-wabah-viru...
1,[BPS: Pertumbuhan Ekonomi Indonesia 2019 Capai...,/play/Ky6Cme5o-bps-pertumbuhan-ekonomi-indones...
2,[Menghitung Dampak Ekonomi Penutupan Penerbang...,/play/kqYComxn-menghitung-dampak-ekonomi-penut...
3,[Virus Corona Ikut Ancam Ekonomi Indonesia],/play/bVDCQrgr-virus-corona-ikut-ancam-ekonomi...
4,[Menghitung Dampak Ekonomi dari Penyebaran Vir...,/play/kBVCRyjL-menghitung-dampak-ekonomi-dari-...

In [97]:
# Mengganti nama kolom
df18.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df18.tail()

,Judul Berita,URL
25,[Asa Ekonomi 2020 (4)],/play/bzGCpjw6-asa-ekonomi-2020-4
26,[Asa Ekonomi 2020 (3)],/play/bw6C570M-asa-ekonomi-2020-3
27,[Asa Ekonomi 2020 (2)],/play/bD2CWyRX-asa-ekonomi-2020-2
28,[Asa Ekonomi 2020 (1)],/play/NLMCRAZo-asa-ekonomi-2020-1
29,[Sosiolog: Kemunculan 'Kerajaan Baru' Bermotif...,/play/NgxCrLpv-sosiolog-kemunculan-kerajaan-ba...

### Halaman 19

In [98]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/18".format(keyword)

In [99]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [100]:
# Memasukkan hasil scraping ke dalam DataFrame
df19 = pd.DataFrame(data)
df19.head()

,0,1
0,[Pemprov Jatim Akan Percepat Pembangunan Ekonomi],/play/KYVC6Wel-pemprov-jatim-akan-percepat-pem...
1,[Sosiolog: Keraton Agung Sejagat Terbentuk Kar...,/play/b7WCO6Og-sosiolog-keraton-agung-sejagat-...
2,[Konflik AS-Iran Tak Pengaruhi Makro Ekonomi I...,/play/kj2C1qqm-konflik-as-iran-tak-pengaruhi-m...
3,"[Kondisi Politik dan Ekonomi Global Membaik, I...",/play/b1oCA21L-kondisi-politik-dan-ekonomi-glo...
4,[Bank Dunia Pangkas Proyeksi Ekonomi 2020],/play/NgxCr39a-bank-dunia-pangkas-proyeksi-eko...

In [102]:
# Mengganti nama kolom
df19.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df19.tail()

,Judul Berita,URL
25,[Jokowi: Pindah Ibu Kota Bukan Hanya Lokasi Ta...,/play/KXyC0ojm-jokowi-pindah-ibu-kota-bukan-ha...
26,[KNKS akan Usulkan UU Ekonomi Syariah],/play/K5nC08G0-knks-akan-usulkan-uu-ekonomi-sy...
27,[Pembangunan Ibu Kota Baru Libatkan Pelaku Eko...,/play/NLMCRPyy-pembangunan-ibu-kota-baru-libat...
28,[Sandiaga Uno Dukung Pemberdayaan Ekonomi Umat],/play/KvJCQDQX-sandiaga-uno-dukung-pemberdayaa...
29,[Dampak Omnibus Law Terhadap Ekonomi Indonesia],/play/KRXCg6GJ-dampak-omnibus-law-terhadap-eko...

### Halaman 20

In [103]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/19".format(keyword)

In [104]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [105]:
# Memasukkan hasil scraping ke dalam DataFrame
df20 = pd.DataFrame(data)
df20.head()

,0,1
0,[Jokowi Ingatkan Semua Elemen Bangsa Jaga Stab...,/play/ba4CVDpo-jokowi-ingatkan-semua-elemen-ba...
1,[Proyeksi Pertumbuhan Ekonomi Indonesia 2020],/play/bJECzOeM-proyeksi-pertumbuhan-ekonomi-in...
2,[Jokowi Prediksi Ekonomi Indonesia 2020 Tumbuh...,/play/ba4CVDRX-jokowi-prediksi-ekonomi-indones...
3,[DPR Temui Parlemen Belgia Bahas Sektor Indust...,/play/koGCG5n7-dpr-temui-parlemen-belgia-bahas...
4,[DPR Temui Parlemen Belgia Bahas Kerja Sama Ek...,/play/b3JCVYGq-dpr-temui-parlemen-belgia-bahas...

In [106]:
# Mengganti nama kolom
df20.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df20.tail()

,Judul Berita,URL
25,[Presiden Jokowi Bertemu IMF Bahas Ekonomi Glo...,/play/b3JCo4Zo-presiden-jokowi-bertemu-imf-bah...
26,[Sektor Infrastruktur Diprediksi Terkena Dampa...,/play/b2lCZeBq-sektor-infrastruktur-diprediksi...
27,[Presiden Jokowi Gelar Ratas Bahas Ekonomi Glo...,/play/KdZCOn5w-presiden-jokowi-gelar-ratas-bah...
28,[Bicara Ekonomi Indonesia (2)],/play/NrWCl7nZ-bicara-ekonomi-indonesia-2
29,[Bicara Ekonomi Indonesia (1)],/play/KRXCGLYg-bicara-ekonomi-indonesia-1

### Halaman 21

In [107]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/20".format(keyword)

In [108]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [109]:
# Memasukkan hasil scraping ke dalam DataFrame
df21 = pd.DataFrame(data)
df21.head()

,0,1
0,[Pasar Modal Indonesia di Tengah Gejolak Ekonomi],/play/KRXCGLxg-pasar-modal-indonesia-di-tengah...
1,[Pencapaian Ekonomi dan Fokus Kerja ke Depan],/play/kELCYZaR-pencapaian-ekonomi-dan-fokus-ke...
2,[Kerja Sama Ekonomi RI-Timor Leste],/play/NA0C7V3o-kerja-sama-ekonomi-ri-timor-leste
3,[Pelaku Pasar Respons Positif Tim Ekonomi Kabi...,/play/N4ECxVaM-pelaku-pasar-respons-positif-ti...
4,[Ekonom: Jokowi Posisikan Orang yang Tepat Duk...,/play/kBVCjYgz-ekonom-jokowi-posisikan-orang-y...

In [110]:
# Mengganti nama kolom
df21.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df21.tail()

,Judul Berita,URL
25,[Kesempatan di Balik Pelemahan Ekonomi Global],/play/NOlCGXgy-kesempatan-di-balik-pelemahan-e...
26,[Pertumbuhan Ekonomi Dunia Terancam Melambat],/play/kj2CL3zP-pertumbuhan-ekonomi-dunia-teran...
27,[Mekah Pusat Ekonomi dan Budaya (3)],/play/kWDC91Xq-mekah-pusat-ekonomi-dan-budaya-3
28,[Mekah Pusat Ekonomi dan Budaya (2)],/play/NnjC5Ayj-mekah-pusat-ekonomi-dan-budaya-2
29,[Mekah Pusat Ekonomi dan Budaya (1)],/play/NA0C7PRX-mekah-pusat-ekonomi-dan-budaya-1

### Halaman 22

In [111]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/21".format(keyword)

In [112]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [113]:
# Memasukkan hasil scraping ke dalam DataFrame
df22 = pd.DataFrame(data)
df22.head()

,0,1
0,[BI: Pertumbuhan Ekonomi Indonesia di Atas Lim...,/play/bw6CjmQM-bi-pertumbuhan-ekonomi-indonesi...
1,[Indonesia Menuju 5 Negara Ekonomi Terbesar Du...,/play/K5nCX348-indonesia-menuju-5-negara-ekono...
2,[Pertumbuhan Ekonomi Indonesia Diyakini Tumbuh...,/play/b2lCZ2Gw-pertumbuhan-ekonomi-indonesia-d...
3,[Kasus Istri Bunuh Suami Dipicu Faktor Ekonomi...,/play/b2lCZxeL-kasus-istri-bunuh-suami-dipicu-...
4,[Kiat Hindari Resesi Ekonomi di Indonesia],/play/k8oC9Mp5-kiat-hindari-resesi-ekonomi-di-...

In [114]:
# Mengganti nama kolom
df22.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df22.tail()

,Judul Berita,URL
25,"[Ekonomi Digital, Mesin Baru Pertumbuhan Ekono...",/play/kpLCow8V-ekonomi-digital-mesin-baru-pert...
26,[Warga Hong Kong Khawatir Ekonomi Terganggu Ak...,/play/NOlCGqO0-warga-hong-kong-khawatir-ekonom...
27,[Pemerintah Andalkan Investasi untuk Hadapi Ge...,/play/b3JCowJ8-pemerintah-andalkan-investasi-u...
28,[Angka Ketimpangan Ekonomi Indonesia Terjaga R...,/play/NA0C7gXl-angka-ketimpangan-ekonomi-indon...
29,[Pertumbuhan Ekonomi Triwulan II Masih Terjaga],/play/NxGCOwR8-pertumbuhan-ekonomi-triwulan-ii...

### Halaman 23

In [115]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/22".format(keyword)

In [116]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [117]:
# Memasukkan hasil scraping ke dalam DataFrame
df23 = pd.DataFrame(data)
df23.head()

,0,1
0,[Pemerintah Dinilai Berhasil Jaga Stabilitas P...,/play/N4ECxe1O-pemerintah-dinilai-berhasil-jag...
1,[Bank Indonesia Gelar Festival Ekonomi Syariah...,/play/NG9CR1Vy-bank-indonesia-gelar-festival-e...
2,[Jokowi akan Fokus Dorong Reformasi Ekonomi],/play/bzGCXdEm-jokowi-akan-fokus-dorong-reform...
3,"[Pascagempa Halmahera Selatan, Aktivitas Ekono...",/play/b2lCZaAR-pascagempa-halmahera-selatan-ak...
4,"[Perkenalkan Potensi Ekonomi, Indonesia Gelar ...",/play/koGCjpMo-perkenalkan-potensi-ekonomi-ind...

In [118]:
# Mengganti nama kolom
df23.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df23.tail()

,Judul Berita,URL
25,[Kegiatan Ekonomi di Kawasan Gedung Bawaslu Su...,/play/KvJCYdBd-kegiatan-ekonomi-di-kawasan-ged...
26,[Dampak Ekonomi Aksi 22 Mei],/play/KYVCn9gA-dampak-ekonomi-aksi-22-mei
27,[Menko Darmin Yakin Aksi 22 Mei Tak Berdampak ...,/play/NLMCjMWO-menko-darmin-yakin-aksi-22-mei-...
28,"[Ekonomi Memburuk, Warga Gaza Batasi Uang Bela...",/play/kpLCoVZy-ekonomi-memburuk-warga-gaza-bat...
29,[Unair Gandeng Guru Besar dari Belanda Kembang...,/play/NleCzxLe-unair-gandeng-guru-besar-dari-b...

### Halaman 24

In [119]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/23".format(keyword)

In [120]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [121]:
# Memasukkan hasil scraping ke dalam DataFrame
df24 = pd.DataFrame(data)
df24.head()

,0,1
0,[Jokowi Luncurkan Masterplan Ekonomi Syariah I...,/play/KXyCY1nP-jokowi-luncurkan-masterplan-eko...
1,[Menakar Masa Depan Ekonomi Indonesia (4)],/play/kBVCjzvO-menakar-masa-depan-ekonomi-indo...
2,[Menakar Masa Depan Ekonomi Indonesia (3)],/play/NQACnwzM-menakar-masa-depan-ekonomi-indo...
3,[Menakar Masa Depan Ekonomi Indonesia (2)],/play/b3JCo0nM-menakar-masa-depan-ekonomi-indo...
4,[Menakar Masa Depan Ekonomi Indonesia (1)],/play/kewCOrZm-menakar-masa-depan-ekonomi-indo...

In [122]:
# Mengganti nama kolom
df24.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df24.tail()

,Judul Berita,URL
25,[Prospek Investasi di Tahun Politik (2)],/play/baGUYMzn-prospek-investasi-di-tahun-poli...
26,[Prospek Investasi di Tahun Politik (1)],/play/kBoUjQ9m-prospek-investasi-di-tahun-poli...
27,[Jembatan Sikundo Diharapkan Genjot Ekonomi Desa],/play/NglU76V0-jembatan-sikundo-diharapkan-gen...
28,[JK Jamin Ekonomi Indonesia Tetap Stabil Jika...,/play/kW0U9woX-jk-jamin-ekonomi-indonesia-teta...
29,"[Berkat Program Mekaar, Warung Kelontong Roeda...",/play/ke4UOyDj-berkat-program-mekaar-warung-ke...

### Halaman 25

In [123]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/24".format(keyword)

In [124]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [125]:
# Memasukkan hasil scraping ke dalam DataFrame
df25 = pd.DataFrame(data)
df25.head()

,0,1
0,[Bekraf Gandeng VIU Bangun Ekosistem Film Indo...,/play/NQoUnEZl-bekraf-gandeng-viu-bangun-ekosi...
1,[Jokowi: Wanita Indonesia adalah Tiang Keluarg...,/play/kqGUG5an-jokowi-wanita-indonesia-adalah-...
2,[Indonesia Klub Elite Dunia (4)],/play/NxXUOBnr-indonesia-klub-elite-dunia-4
3,[Indonesia Klub Elite Dunia (3)],/play/K5WUXngz-indonesia-klub-elite-dunia-3
4,[Indonesia Klub Elite Dunia (2)],/play/KXXUYjPg-indonesia-klub-elite-dunia-2

In [126]:
# Mengganti nama kolom
df25.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df25.tail()

,Judul Berita,URL
25,[Ma'ruf Amin Janji Kembangkan Fintech Berbasis...,/play/NnGU5Vvr-ma-ruf-amin-janji-kembangkan-fi...
26,[Ma'ruf Amin Dorong Pengembangan Fintech Syariah],/play/NlxUzoLl-ma-ruf-amin-dorong-pengembangan...
27,[Ridwan Kamil Geliatkan Ekonomi Kreatif di Jabar],/play/NlxUzml6-ridwan-kamil-geliatkan-ekonomi-...
28,[Jokowi: Kita Harus Optimis Menatap Masa Depan...,/play/N0oUGp6X-jokowi-kita-harus-optimis-menat...
29,[Dampak Ekonomi Perayaan Imlek di Surakarta],/play/bD7Up5py-dampak-ekonomi-perayaan-imlek-d...

### Halaman 26

In [127]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/25".format(keyword)

In [128]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [129]:
# Memasukkan hasil scraping ke dalam DataFrame
df26 = pd.DataFrame(data)
df26.head()

,0,1
0,[KH Ma'ruf Amin Kunjungi Keluarga Bung Hatta],/play/KY4UnlRB-kh-ma-ruf-amin-kunjungi-keluarg...
1,[Waspadai Jebakan Middle Income],/play/bmGU61Wq-waspadai-jebakan-middle-income
2,[Siapa Untung dari Isu Utang dan Impor?],/play/kM3UzjLy-siapa-untung-dari-isu-utang-dan...
3,[Pertumbuhan Ekonomi Indonesia Diapresiasi Neg...,/play/NglU7PoL-pertumbuhan-ekonomi-indonesia-d...
4,[Rilis Pertumbuhan Ekonomi Buat IHSG Makin Mel...,/play/bzYUXWVy-rilis-pertumbuhan-ekonomi-buat-...

In [130]:
# Mengganti nama kolom
df26.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df26.tail()

,Judul Berita,URL
25,[Bedah Editorial MI: Revolusi Energi],/play/KRoUGDDy-bedah-editorial-mi-revolusi-energi
26,[Revolusi Energi],/play/NxXUOEE4-revolusi-energi
27,[Indonesia Bawa Sejumlah Misi ke World Economi...,/play/NP5UjBVG-indonesia-bawa-sejumlah-misi-ke...
28,[Pergerakan Bursa Saham dan Rupiah],/play/K5WUXA8q-pergerakan-bursa-saham-dan-rupiah
29,[Infrastruktur Dorong Pertumbuhan Ekonomi Daerah],/play/N0oUG8n8-infrastruktur-dorong-pertumbuha...

### Halaman 27

In [131]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/26".format(keyword)

In [132]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [133]:
# Memasukkan hasil scraping ke dalam DataFrame
df27 = pd.DataFrame(data)
df27.head()

,0,1
0,"[Menko Maritim, Menperin, Menkominfo dan Ketua...",/play/NGEURZPv-menko-maritim-menperin-menkomin...
1,[Wisata Swafoto di Lokasi Bisnis Bunga],/play/bD7UpQOW-wisata-swafoto-di-lokasi-bisnis...
2,[Pertumbuhan Ekonomi Tiongkok Menurun],/play/b18UXPnz-pertumbuhan-ekonomi-tiongkok-me...
3,[Wisata Swafoto di Lokasi Bisnis Bunga],/play/bwGUjV0R-wisata-swafoto-di-lokasi-bisnis...
4,[Lima Pilar Jaga Indonesia (1)],/play/kEmUY2nm-lima-pilar-jaga-indonesia-1

In [134]:
# Mengganti nama kolom
df27.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df27.tail()

,Judul Berita,URL
25,[Kinerja APBN dan Pertumbuhan Ekonomi di Tahun...,/play/NglU7l4L-kinerja-apbn-dan-pertumbuhan-ek...
26,[Dana Subsidi KA Ekonomi Naik],/play/NOZUGyJw-dana-subsidi-ka-ekonomi-naik
27,[Bedah Editorial: Penerimaan Tembus Target],/play/b3lUo9w3-bedah-editorial-penerimaan-temb...
28,[Penerimaan Tembus Target],/play/NL0Ujzv0-penerimaan-tembus-target
29,[Wajah Indonesia 2019 - Menerbangkan Indonesia...,/play/KY4Un0l2-wajah-indonesia-2019-menerbangk...

### Halaman 28

In [135]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/27".format(keyword)

In [136]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [137]:
# Memasukkan hasil scraping ke dalam DataFrame
df28 = pd.DataFrame(data)
df28.head()

,0,1
0,[Wajah Indonesia 2019 - Menerbangkan Indonesia...,/play/NOZUGyoE-wajah-indonesia-2019-menerbangk...
1,[Wajah Indonesia 2019 - Menerbangkan Indonesia...,/play/bD7Up85B-wajah-indonesia-2019-menerbangk...
2,[Wajah Indonesia 2019 - Menerbangkan Indonesia...,/play/NL0UjzmZ-wajah-indonesia-2019-menerbangk...
3,[Wajah Indonesia 2019: CSV Nilai Baru Sosial E...,/play/NP5UjPRA-wajah-indonesia-2019-csv-nilai-...
4,[Wajah Indonesia 2019: CSV Nilai Baru Sosial E...,/play/N6MU4XYA-wajah-indonesia-2019-csv-nilai-...

In [138]:
# Mengganti nama kolom
df28.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df28.tail()

,Judul Berita,URL
25,[KEK Tanjung Lesung Pascatsunami],/play/ke4UOjje-kek-tanjung-lesung-pascatsunami
26,[Moeldoko Tanam Benih Bawang Putih di Lombok],/play/bVLUwPgx-moeldoko-tanam-benih-bawang-put...
27,[Potensi Produk Halal Indonesia],/play/KZ7U0V7o-potensi-produk-halal-indonesia
28,[Taktik Pindah Transportasi Umum ala Jepang],/play/KZ7U0Vmj-taktik-pindah-transportasi-umum...
29,[Komunitas Selaras Alam Mengolah Kopi Jadi Pen...,/play/koYUjd1q-komunitas-selaras-alam-mengolah...

### Halaman 29

In [139]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/28".format(keyword)

In [140]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [141]:
# Memasukkan hasil scraping ke dalam DataFrame
df29 = pd.DataFrame(data)
df29.head()

,0,1
0,[Proyeksi Perekonomian Nasional],/play/KyQU61YA-proyeksi-perekonomian-nasional
1,[Ekonomi Jadi Isu Seksi Dimainkan Jelang Penco...,/play/KY4Un4QD-ekonomi-jadi-isu-seksi-dimainka...
2,[Trans Jawa Diharap Bisa Berintegrasi dengan K...,/play/NGEURQZe-trans-jawa-diharap-bisa-berinte...
3,[Kadin Prediksi Ekonomi Jakarta Tumbuh 6% di 2...,/play/NxXUOG5J-kadin-prediksi-ekonomi-jakarta-...
4,[Syiar Sirah Nabawiyah: Sirah Rasul Rekaman Pe...,/play/KRoUG5MO-syiar-sirah-nabawiyah-sirah-ras...

In [142]:
# Mengganti nama kolom
df29.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df29.tail()

,Judul Berita,URL
25,[Pertukaran Budaya Indonesia-Jepang],/play/b3lUoryE-pertukaran-budaya-indonesia-jepang
26,[Balita Tiga Tahun di Balikpapan Mengalami Kel...,/play/N6MU4g0O-balita-tiga-tahun-di-balikpapan...
27,[IHSG dan Rupiah Diprediksi Lanjutkan Penguatan],/play/KY4UnDV5-ihsg-dan-rupiah-diprediksi-lanj...
28,[Jokowi Buka Rakernas Asparindo 2018],/play/koYUjVnA-jokowi-buka-rakernas-asparindo-...
29,[Singularitas Ekonomi Indonesia],/play/ke4UOlAQ-singularitas-ekonomi-indonesia

### Halaman 30

In [143]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/29".format(keyword)

In [144]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [145]:
# Memasukkan hasil scraping ke dalam DataFrame
df30 = pd.DataFrame(data)
df30.head()

,0,1
0,[BI Menjawab Tantangan Ekonomi 2019],/play/bVLUwOEq-bi-menjawab-tantangan-ekonomi-2019
1,[Teka-teki Ekonomi 2019 (4)],/play/kpXUorEJ-teka-teki-ekonomi-2019-4
2,[Teka-teki Ekonomi 2019 (3)],/play/kEmUY1JR-teka-teki-ekonomi-2019-3
3,[Teka-teki Ekonomi 2019 (2)],/play/N4lUx2wG-teka-teki-ekonomi-2019-2
4,[Teka-teki Ekonomi 2019 (1)],/play/bJ4UYnPB-teka-teki-ekonomi-2019-1

In [146]:
# Mengganti nama kolom
df30.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df30.tail()

,Judul Berita,URL
25,[IHSG dan Rupiah Diprediksi Tertahan di Zona M...,/play/N98U4vA7-ihsg-dan-rupiah-diprediksi-tert...
26,[Daftar Proyek Strategis Nasional di Provinsi ...,/play/b2vUZOZ5-daftar-proyek-strategis-nasiona...
27,[Gali Kreativitas Anak Disabilitas],/play/NOZUGGR0-gali-kreativitas-anak-disabilitas
28,['Komoditas Politik Soeharto' di Pilpres 2019],/play/KyQU66aq-komoditas-politik-soeharto-di-p...
29,[Jejak Prestasi dan Pola KKN Orde Baru],/play/NGEURRDz-jejak-prestasi-dan-pola-kkn-ord...

### Halaman 31

In [152]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/30".format(keyword)

In [153]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [154]:
# Memasukkan hasil scraping ke dalam DataFrame
df31 = pd.DataFrame(data)
df31.head()

,0,1
0,[Pertunjukan Teater Musikal Nusantara],/play/KvWUYY7M-pertunjukan-teater-musikal-nusa...
1,[Hasil Kesepakatan KTT G20 2018],/play/NOZUGGBB-hasil-kesepakatan-ktt-g20-2018
2,"[Mendag Rampungkan IE-CEPA, Akses Pasar Indone...",/play/NL0Ujjey-mendag-rampungkan-ie-cepa-akses...
3,[Lopez Obrador Dilantik Jadi Presiden Meksiko],/play/NxXUOOwl-lopez-obrador-dilantik-jadi-pre...
4,[Sambungan Listrik Dukung Ekonomi Desa],/play/KY4Unn24-sambungan-listrik-dukung-ekonom...

In [155]:
# Mengganti nama kolom
df31.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df31.tail()

,Judul Berita,URL
25,[Kerajinan Karya Warga Binaan],/play/N6MU4AYE-kerajinan-karya-warga-binaan
26,[Manfaat Industri Kesehatan Digital di Era Mil...,/play/NAvU7OBn-manfaat-industri-kesehatan-digi...
27,[Manfaat Industri Kesehatan Digital di Era Mil...,/play/K5WUXJg2-manfaat-industri-kesehatan-digi...
28,[Manfaat Industri Kesehatan Digital di Era Mil...,/play/KZ7U0xoE-manfaat-industri-kesehatan-digi...
29,[Arus Mudik Thanksgiving di Amerika Serikat],/play/NP5UjrPP-arus-mudik-thanksgiving-di-amer...

### Halaman 32

In [156]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/31".format(keyword)

In [157]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [158]:
# Memasukkan hasil scraping ke dalam DataFrame
df32 = pd.DataFrame(data)
df32.head()

,0,1
0,[Meraup Pundi-punci Uang Ekonomi Digital],/play/NlxUzG7D-meraup-pundi-punci-uang-ekonomi...
1,[BI Goes to Universitas Pattimura],/play/KZ7U0xWA-bi-goes-to-universitas-pattimura
2,[Caleg Parpol Pendukung Jokowi-Ma'ruf Door to ...,/play/Kd4UO24P-caleg-parpol-pendukung-jokowi-m...
3,[Jokowi: Kebijakan Ekonomi Harus Perkuat UMKM],/play/NAvU7w0r-jokowi-kebijakan-ekonomi-harus-...
4,[Pemerintah akan Rilis Aturan Energi Ramah Lin...,/play/bzYUX08W-pemerintah-akan-rilis-aturan-en...

In [159]:
# Mengganti nama kolom
df32.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df32.tail()

,Judul Berita,URL
25,[Bank Indonesia Goes to Campus Palembang],/play/NglU7B1B-bank-indonesia-goes-to-campus-p...
26,"[Pembunuhan Sekeluarga di Bekasi, Polisi Perlu...",/play/NP5UjyBq-pembunuhan-sekeluarga-di-bekasi...
27,[Pembunuhan Keluarga di Bekasi Diduga Bukan Mo...,/play/NP5UjyPg-pembunuhan-keluarga-di-bekasi-d...
28,[Jokowi Mewakili ASEAN Bertemu Rusia],/play/NnGU5p4Q-jokowi-mewakili-asean-bertemu-r...
29,[Setahun Tersisa Jokowi-JK (3)],/play/ke4UOLXx-setahun-tersisa-jokowi-jk-3

### Halaman 33

In [160]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/32".format(keyword)

In [161]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [162]:
# Memasukkan hasil scraping ke dalam DataFrame
df33 = pd.DataFrame(data)
df33.head()

,0,1
0,[Setahun Tersisa Jokowi-JK (4)],/play/b3lUovVe-setahun-tersisa-jokowi-jk-4
1,[Rumusan RCEP Belum Disetujui Sejumlah Negara],/play/NlxUzrrE-rumusan-rcep-belum-disetujui-se...
2,[Agenda Utama Indonesia di KTT ASEAN 2018],/play/kqGUGpO3-agenda-utama-indonesia-di-ktt-a...
3,[Jokowi Dorong Pembahasan Indo Pasifik di KTT ...,/play/KvWUYeVo-jokowi-dorong-pembahasan-indo-p...
4,[Indonesia Ingin Percepat Penyelesaian RCEP],/play/kj5ULeao-indonesia-ingin-percepat-penyel...

In [163]:
# Mengganti nama kolom
df33.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df33.tail()

                      Judul Berita                                        URL
25              [Diplomasi Busana]            /play/b2vUZGOR-diplomasi-busana
26    [Semangat Berbagi Hoshizora]  /play/KRoUGngr-semangat-berbagi-hoshizora
27  [Menuju Peradaban Digital (3)]  /play/b3lUoEej-menuju-peradaban-digital-3
28  [Menuju Peradaban Digital (2)]  /play/ke4UOxQv-menuju-peradaban-digital-2
29  [Menuju Peradaban Digital (1)]  /play/bmGU63LJ-menuju-peradaban-digital-1

### Halaman 34

In [164]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/33".format(keyword)

In [165]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [166]:
# Memasukkan hasil scraping ke dalam DataFrame
df34 = pd.DataFrame(data)
df34.head()

,0,1
0,[Bedah Editorial: Jembatan Penghapus Ketimpangan],/play/NQoUnlLw-bedah-editorial-jembatan-pengha...
1,[Jembatan Penghapus Ketimpangan],/play/Nr4UlPQO-jembatan-penghapus-ketimpangan
2,[Ketika Perusahaan-perusahaan Asing Dinasional...,/play/bwGUjalB-ketika-perusahaan-perusahaan-as...
3,[Ketika Perusahaan-perusahaan Asing Dinasional...,/play/bD7UpoD3-ketika-perusahaan-perusahaan-as...
4,[Ketika Perusahaan-perusahaan Asing Dinasional...,/play/NL0Uj0or-ketika-perusahaan-perusahaan-as...

In [167]:
# Mengganti nama kolom
df34.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df34.tail()

,Judul Berita,URL
25,"[BI Pertahankan Suku Bunga Acuan di 5,75%]",/play/KvWUY1G5-bi-pertahankan-suku-bunga-acuan...
26,[Mendag Ingatkan Tantangan Ekonomi Global],/play/bD7UpyOM-mendag-ingatkan-tantangan-ekono...
27,[Hampir 70% Rakyat Indonesia Puas dengan Kiner...,/play/b7yUq67M-hampir-70-rakyat-indonesia-puas...
28,"[Abdul Wahab, Menebar Rahmat Bagi Semesta]",/play/N4lUxB7e-abdul-wahab-menebar-rahmat-bagi...
29,[Dampak Pelemahan Ekonomi Tiongkok pada Indone...,/play/KRoUG3E3-dampak-pelemahan-ekonomi-tiongk...

### Halaman 35

In [168]:
# Copy URL Website
keyword = "ekonomi"
url = "https://www.metrotvnews.com/search/{}/34".format(keyword)

In [169]:
# Request URL Website
req = requests.get(url)

# Parsing HTML ke dalam BeautifulSoup
soup = bs(req.text, "html.parser")

# Memanggil judul artikel
article = soup.findAll("div", "item")

# List kosong
data = []

for scraping in article:
    text = scraping.find("h3").text.strip().split("\n")
    link = scraping.find("a")["href"]
    
    data.append([text, link]) # Memasukkan data scraping ke dalam list data

In [170]:
# Memasukkan hasil scraping ke dalam DataFrame
df35 = pd.DataFrame(data)
df35.head()

,0,1
0,[Moeldoko: Pemerintahan Jokowi-JK Turunkan Ang...,/play/NP5UjmRw-moeldoko-pemerintahan-jokowi-jk...
1,[Jokowi Tegaskan Kondisi Ekonomi Saat Ini Berb...,/play/Kd4UOlVq-jokowi-tegaskan-kondisi-ekonomi...
2,[Pidato 'Game of Thrones' Jokowi Buat Milenial...,/play/kqGUGVEn-pidato-game-of-thrones-jokowi-b...
3,[Ini Pencapaian Terbesar Empat Tahun Pemerinta...,/play/b18UXg8z-ini-pencapaian-terbesar-empat-t...
4,[Pengamat Menilai Penyesuaikan Harga BBM Hal B...,/play/NnGU5vZn-pengamat-menilai-penyesuaikan-h...

In [171]:
# Mengganti nama kolom
df35.rename(columns={0: "Judul Berita", 1:"URL"}, inplace=True)
df35.tail()

,Judul Berita,URL
25,[IMF Serukan Kerja Sama Global Menjaga Ekonomi],/play/NnGU5JE1-imf-serukan-kerja-sama-global-m...
26,[Rehabilitasi Infrastruktur Pascagempa Sulteng...,/play/N98U4w5n-rehabilitasi-infrastruktur-pasc...
27,[Wawancara Khusus Bersama Direktur Pelaksana I...,/play/N0oUG2an-wawancara-khusus-bersama-direkt...
28,[Wawancara Khusus Bersama Direktur Pelaksana I...,/play/Kd4UORyG-wawancara-khusus-bersama-direkt...
29,[Wawancara Khusus Bersama Direktur Pelaksana I...,/play/b7yUqM7o-wawancara-khusus-bersama-direkt...

### Menggabungkan 35 DataFrame Menjadi 1

In [172]:
# Membuat DataFrame baru untuk menampung DataFrame hasil scraping
df_sementara = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20,
               df21, df22, df23, df24, df25, df26, df27, df28, df29, df30, df31, df32, df33, df34, df35]

# Menggabungkan DataFrame dengan 2 kolom di dalamnya
df_final = pd.concat(df_sementara)

df_final.head()

,Judul Berita,URL
0,[Pelaksanaan PON XX Beri Dampak Ekonomi bagi M...,/play/b1oCAJZL-pelaksanaan-pon-xx-beri-dampak-...
1,[Harga Minyak Tinggi Bisa Hambat Pemulihan Eko...,/play/NxGCymm4-harga-minyak-tinggi-bisa-hambat...
2,[IMF Pangkas Proyeksi Pertumbuhan Ekonomi Glob...,/play/NleC6BQ2-imf-pangkas-proyeksi-pertumbuha...
3,[Cerita Gagastama Peraih Beasiswa OSC: Tetap B...,/play/koGCG96P-cerita-gagastama-peraih-beasisw...
4,[Kawasan Ekonomi Khusus JIIPE Gresik Resmi Ber...,/play/bmRCy0Dn-kawasan-ekonomi-khusus-jiipe-gr...

In [173]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1050 entries, 0 to 29
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Judul Berita  1050 non-null   object
 1   URL           1050 non-null   object
dtypes: object(2)
memory usage: 24.6+ KB

In [174]:
# Menjadikan ke dalam format .csv
df_final.to_csv("Data Scraping (Metro TV News) - Ekonomi.csv", index=False)